//! Per-family glyph advances for the fonts a macOS Chrome profile claims.
//!
//! Harvested from a real Chrome 151 on macOS (`measureText` at 1000px, ASCII
//! 32..=126) and stored as exact font design units — every advance came back
//! integral, so nothing is rounded here. Widths travel with the profile
//! instead of being read off whatever the host machine has installed, which is
//! what the old `system_fonts` module did.
//!
//! Chrome resolves the first *installed* family in a CSS list and falls back to
//! its default (Times) when none match, so an unknown family measures like
//! Times there — `lookup` reproduces that rather than inventing a width.
//!
//! Generated by `camoufox-lab/fontmetrics/gen.py` from `macos.json`.

/// Advances for ASCII 32..=126, in font design units at `upem`.
pub struct FamilyMetrics {
    pub upem: u16,
    pub advances: [u16; 95],
}

static ARIAL: FamilyMetrics = FamilyMetrics {
    upem: 2048,
    advances: [
        569, 569, 727, 1139, 1139, 1821, 1366, 391, 682, 682, 797, 1196, 569, 682, 569, 569, 1139,
        1139, 1139, 1139, 1139, 1139, 1139, 1139, 1139, 1139, 569, 569, 1196, 1196, 1196, 1139,
        2079, 1366, 1366, 1479, 1479, 1366, 1251, 1593, 1479, 569, 1024, 1366, 1139, 1706, 1479,
        1593, 1366, 1593, 1479, 1366, 1251, 1479, 1366, 1933, 1366, 1366, 1251, 569, 569, 569, 961,
        1139, 682, 1139, 1139, 1024, 1139, 1139, 569, 1139, 1139, 455, 455, 1024, 455, 1706, 1139,
        1139, 1139, 1139, 682, 1024, 569, 1139, 1024, 1479, 1024, 1024, 1024, 684, 532, 684, 1196,
    ],
};

static ARIAL_BLACK: FamilyMetrics = FamilyMetrics {
    upem: 2048,
    advances: [
        683, 682, 1024, 1352, 1366, 2048, 1821, 569, 797, 797, 1139, 1352, 682, 682, 682, 569,
        1366, 1366, 1366, 1366, 1366, 1366, 1366, 1366, 1366, 1366, 682, 682, 1352, 1352, 1352,
        1251, 1516, 1593, 1593, 1593, 1593, 1479, 1366, 1706, 1706, 797, 1366, 1706, 1366, 1933,
        1706, 1706, 1479, 1706, 1593, 1479, 1479, 1706, 1593, 2048, 1593, 1593, 1479, 797, 569,
        797, 1352, 1024, 682, 1366, 1366, 1366, 1366, 1366, 797, 1366, 1366, 682, 682, 1366, 682,
        2048, 1366, 1366, 1366, 1366, 909, 1251, 909, 1366, 1251, 1933, 1366, 1251, 1139, 797, 569,
        797, 1352,
    ],
};

static COMIC_SANS_MS: FamilyMetrics = FamilyMetrics {
    upem: 2048,
    advances: [
        612, 487, 869, 1726, 1420, 1680, 1340, 795, 750, 750, 1085, 984, 567, 853, 510, 1048, 1250,
        922, 1250, 1250, 1250, 1250, 1250, 1250, 1250, 1250, 612, 612, 781, 1045, 781, 1073, 1907,
        1498, 1291, 1234, 1478, 1279, 1243, 1392, 1573, 1119, 1362, 1251, 1128, 1808, 1632, 1635,
        1066, 1795, 1287, 1420, 1392, 1509, 1331, 2129, 1482, 1301, 1420, 771, 1126, 771, 1190,
        1284, 1139, 1048, 1215, 1052, 1203, 1122, 1041, 1087, 1183, 574, 826, 1106, 561, 1591,
        1072, 1077, 1095, 1065, 984, 997, 965, 1065, 996, 1401, 1209, 1066, 1102, 750, 863, 750,
        1224,
    ],
};

static COURIER_NEW: FamilyMetrics = FamilyMetrics {
    upem: 2048,
    advances: [
        1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229,
        1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229,
        1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229,
        1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229,
        1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229,
        1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229,
        1229, 1229, 1229, 1229, 1229,
    ],
};

static GEORGIA: FamilyMetrics = FamilyMetrics {
    upem: 2048,
    advances: [
        494, 678, 843, 1317, 1249, 1674, 1455, 441, 768, 768, 967, 1317, 552, 766, 552, 960, 1257,
        880, 1144, 1130, 1157, 1082, 1159, 1029, 1221, 1159, 640, 640, 1317, 1317, 1317, 980, 1902,
        1374, 1339, 1315, 1534, 1338, 1227, 1485, 1669, 798, 1060, 1422, 1236, 1899, 1571, 1524,
        1249, 1524, 1437, 1149, 1267, 1549, 1365, 1998, 1455, 1260, 1232, 768, 960, 768, 1317,
        1317, 1024, 1032, 1147, 930, 1176, 990, 666, 1043, 1192, 600, 598, 1097, 586, 1804, 1210,
        1104, 1170, 1146, 839, 885, 707, 1178, 1017, 1510, 1034, 1008, 909, 881, 768, 881, 1317,
    ],
};

static HELVETICA_NEUE: FamilyMetrics = FamilyMetrics {
    upem: 1000,
    advances: [
        278, 259, 426, 556, 556, 1000, 630, 278, 259, 259, 352, 600, 278, 389, 278, 333, 556, 556,
        556, 556, 556, 556, 556, 556, 556, 556, 278, 278, 600, 600, 600, 556, 800, 648, 685, 722,
        704, 611, 574, 759, 722, 259, 519, 667, 556, 871, 722, 760, 648, 760, 685, 648, 574, 722,
        611, 926, 611, 648, 611, 259, 333, 259, 600, 500, 222, 537, 593, 537, 593, 537, 296, 574,
        556, 222, 222, 519, 222, 853, 556, 574, 593, 593, 333, 500, 315, 556, 500, 758, 518, 500,
        480, 333, 222, 333, 600,
    ],
};

static IMPACT: FamilyMetrics = FamilyMetrics {
    upem: 2048,
    advances: [
        361, 553, 757, 1283, 1121, 1419, 1180, 379, 642, 642, 575, 1092, 344, 603, 378, 810, 1098,
        780, 1028, 1086, 1023, 1099, 1109, 802, 1095, 1109, 414, 414, 1092, 1092, 1092, 1075, 1587,
        1040, 1131, 1134, 1132, 851, 815, 1129, 1137, 590, 678, 1099, 779, 1468, 1109, 1119, 1028,
        1119, 1103, 1059, 944, 1120, 1072, 1668, 988, 969, 813, 578, 810, 578, 990, 1131, 683,
        1032, 1064, 1013, 1064, 1047, 592, 1062, 1073, 561, 573, 979, 561, 1579, 1071, 1047, 1063,
        1061, 733, 964, 624, 1070, 895, 1371, 888, 918, 719, 757, 555, 757, 1075,
    ],
};

static LUCIDA_GRANDE: FamilyMetrics = FamilyMetrics {
    upem: 2048,
    advances: [
        648, 648, 765, 1295, 1295, 1369, 1428, 469, 666, 666, 987, 1628, 648, 1185, 648, 1074,
        1295, 1295, 1295, 1295, 1295, 1295, 1295, 1295, 1295, 1295, 648, 648, 1628, 1628, 1628,
        864, 1758, 1413, 1178, 1417, 1534, 1110, 1098, 1480, 1505, 590, 637, 1337, 1092, 1764,
        1513, 1591, 1132, 1591, 1295, 1103, 1295, 1419, 1339, 1752, 1282, 1276, 1238, 666, 1074,
        666, 1295, 1024, 1258, 1131, 1289, 1049, 1289, 1141, 753, 1277, 1271, 592, 623, 1197, 592,
        1912, 1271, 1258, 1289, 1289, 838, 1044, 766, 1271, 1060, 1578, 1256, 1070, 1174, 666, 765,
        666, 1295,
    ],
};

static MENLO: FamilyMetrics = FamilyMetrics {
    upem: 2048,
    advances: [
        1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233,
        1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233,
        1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233,
        1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233,
        1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233,
        1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233, 1233,
        1233, 1233, 1233, 1233, 1233,
    ],
};

static MONACO: FamilyMetrics = FamilyMetrics {
    upem: 2048,
    advances: [
        1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229,
        1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229,
        1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229,
        1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229,
        1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229,
        1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229, 1229,
        1229, 1229, 1229, 1229, 1229,
    ],
};

static TIMES_NEW_ROMAN: FamilyMetrics = FamilyMetrics {
    upem: 2048,
    advances: [
        512, 682, 836, 1024, 1024, 1706, 1593, 369, 682, 682, 1024, 1155, 512, 682, 512, 569, 1024,
        1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 569, 569, 1155, 1155, 1155, 909,
        1886, 1479, 1366, 1366, 1479, 1251, 1139, 1479, 1479, 682, 797, 1479, 1251, 1821, 1479,
        1479, 1139, 1479, 1366, 1139, 1251, 1479, 1479, 1933, 1479, 1479, 1251, 682, 569, 682, 961,
        1024, 682, 909, 1024, 909, 1024, 909, 682, 1024, 1024, 569, 569, 1024, 569, 1593, 1024,
        1024, 1024, 1024, 682, 797, 569, 1024, 1024, 1479, 1024, 1024, 909, 983, 410, 983, 1108,
    ],
};

static TREBUCHET_MS: FamilyMetrics = FamilyMetrics {
    upem: 2048,
    advances: [
        617, 752, 665, 1074, 1074, 1229, 1446, 327, 752, 752, 752, 1074, 752, 752, 752, 1074, 1074,
        1074, 1074, 1074, 1074, 1074, 1074, 1074, 1074, 1074, 752, 752, 1074, 1074, 1074, 752,
        1578, 1208, 1159, 1225, 1256, 1097, 1075, 1385, 1340, 570, 976, 1179, 1037, 1453, 1307,
        1380, 1142, 1384, 1192, 985, 1189, 1328, 1203, 1745, 1140, 1168, 1127, 752, 728, 752, 1074,
        1074, 1074, 1076, 1141, 1014, 1141, 1117, 757, 1028, 1119, 584, 751, 1033, 604, 1700, 1119,
        1099, 1141, 1141, 796, 829, 812, 1119, 1003, 1524, 1026, 1010, 972, 752, 1074, 752, 1074,
    ],
};

static VERDANA: FamilyMetrics = FamilyMetrics {
    upem: 2048,
    advances: [
        720, 806, 940, 1676, 1302, 2204, 1488, 550, 930, 930, 1302, 1676, 745, 930, 745, 930, 1302,
        1302, 1302, 1302, 1302, 1302, 1302, 1302, 1302, 1302, 930, 930, 1676, 1676, 1676, 1117,
        2048, 1400, 1404, 1430, 1578, 1295, 1177, 1588, 1539, 862, 931, 1419, 1140, 1726, 1532,
        1612, 1235, 1612, 1424, 1400, 1262, 1499, 1400, 2025, 1403, 1260, 1403, 930, 930, 930,
        1676, 1302, 1302, 1230, 1276, 1067, 1276, 1220, 720, 1276, 1296, 562, 705, 1212, 562, 1992,
        1296, 1243, 1276, 1276, 874, 1067, 807, 1296, 1212, 1676, 1212, 1212, 1076, 1300, 930,
        1300, 1676,
    ],
};

/// Family name (lowercased) to metrics. Includes the generic aliases and the
/// families Chrome resolves to an identical face.
static MACOS: &[(&str, &FamilyMetrics)] = &[
    ("arial", &ARIAL),
    ("arial black", &ARIAL_BLACK),
    ("comic sans ms", &COMIC_SANS_MS),
    ("courier new", &COURIER_NEW),
    ("georgia", &GEORGIA),
    ("helvetica neue", &HELVETICA_NEUE),
    ("impact", &IMPACT),
    ("lucida grande", &LUCIDA_GRANDE),
    ("menlo", &MENLO),
    ("monaco", &MONACO),
    ("times new roman", &TIMES_NEW_ROMAN),
    ("trebuchet ms", &TREBUCHET_MS),
    ("verdana", &VERDANA),
    ("helvetica", &ARIAL),
    ("monaco", &COURIER_NEW),
    ("monospace", &MENLO),
    ("sans-serif", &ARIAL),
    ("serif", &TIMES_NEW_ROMAN),
];

/// Chrome's default face when nothing in the family list resolves.
static MACOS_DEFAULT: &FamilyMetrics = &TIMES_NEW_ROMAN;

fn key_of(family: &str) -> String {
    family.trim().trim_matches(['"', '\'']).to_ascii_lowercase()
}

/// First family in `families` this profile claims, else the OS default.
/// `None` for a profile whose OS has no table yet, leaving the shaped face's
/// own advances in place.
pub fn lookup(families: &[String], os_name: &str) -> Option<&'static FamilyMetrics> {
    if os_name != "macOS" {
        return None;
    }
    for family in families {
        let key = key_of(family);
        if let Some((_, m)) = MACOS.iter().find(|(n, _)| *n == key) {
            return Some(m);
        }
    }
    Some(MACOS_DEFAULT)
}

/// Advance for one ASCII byte, in px at `size_px`.
pub fn advance_px(m: &FamilyMetrics, byte: u8, size_px: f32) -> Option<f32> {
    if !(32..=126).contains(&byte) {
        return None;
    }
    Some(m.advances[(byte - 32) as usize] as f32 * size_px / m.upem as f32)
}

/// Whether the profile genuinely claims `family` — the generic aliases and the
/// default fallback deliberately do not count. Backs `FontFace.load()`'s
/// `local()` check, where answering "installed" for every probed name is
/// itself the tell.
pub fn is_claimed(family: &str, os_name: &str) -> bool {
    if os_name != "macOS" {
        return false;
    }
    matches!(
        key_of(family).as_str(),
        "arial"
            | "arial black"
            | "comic sans ms"
            | "courier new"
            | "georgia"
            | "helvetica"
            | "helvetica neue"
            | "impact"
            | "lucida grande"
            | "menlo"
            | "monaco"
            | "times new roman"
            | "trebuchet ms"
            | "verdana"
    )
}

/// The claimed set, for keeping the JS-side font list in sync.
pub const CLAIMED_MACOS: &[&str] = &[
    "arial",
    "arial black",
    "comic sans ms",
    "courier new",
    "georgia",
    "helvetica",
    "helvetica neue",
    "impact",
    "lucida grande",
    "menlo",
    "monaco",
    "times new roman",
    "trebuchet ms",
    "verdana",
];
